//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCw {
    
    public partial class MovieTheatreOccupancy {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlMovie;
        
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        protected global::System.Web.UI.WebControls.Panel pnlError;
        
        protected global::System.Web.UI.WebControls.Label lblErrorMessage;

        protected global::System.Web.UI.WebControls.Panel pnlMovieInfo;
        
        protected global::System.Web.UI.WebControls.Label lblMovieId;
        
        protected global::System.Web.UI.WebControls.Label lblMovieTitle;
        
        protected global::System.Web.UI.WebControls.Label lblMovieGenre;
        
        protected global::System.Web.UI.WebControls.Label lblMovieLang;
        
        protected global::System.Web.UI.WebControls.Label lblMovieDuration;
        
        protected global::System.Web.UI.WebControls.Label lblMovieRelease;
        
        protected global::System.Web.UI.WebControls.Panel pnlTop3;
        
        protected global::System.Web.UI.WebControls.Repeater rptTop3;
        
        protected global::System.Web.UI.WebControls.Panel pnlNoResults;
        
        protected global::System.Web.UI.WebControls.Panel pnlNoData;
    }
}
