//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCw {
    
    public partial class TheatreCityHallMovie {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlTheatre;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlHall;
        
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        protected global::System.Web.UI.WebControls.Panel pnlHallInfo;
        
        protected global::System.Web.UI.WebControls.Label lblTheatreName;
        
        protected global::System.Web.UI.WebControls.Label lblTheatreCity;
        
        protected global::System.Web.UI.WebControls.Label lblHallNumber;
        
        protected global::System.Web.UI.WebControls.Label lblHallCapacity;
        
        protected global::System.Web.UI.WebControls.GridView gvMovieShowtime;
        
        protected global::System.Web.UI.WebControls.Panel pnlNoData;
    }
}
