//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCw
{


    public partial class Ticket
    {

        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected global::System.Web.UI.WebControls.FormView FormView1;
    }
}
