//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCw {
    
    public partial class UserTicket {
        
        protected global::System.Web.UI.WebControls.DropDownList ddlUser;
        
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        protected global::System.Web.UI.WebControls.Panel pnlError;

        protected global::System.Web.UI.WebControls.Label lblErrorMessage;
        
        protected global::System.Web.UI.WebControls.Panel pnlUserInfo;
        
        protected global::System.Web.UI.WebControls.Label lblUserId;
        
        protected global::System.Web.UI.WebControls.Label lblUserName;
        
        protected global::System.Web.UI.WebControls.Label lblUserEmail;
        
        protected global::System.Web.UI.WebControls.Label lblUserPhone;
        
        protected global::System.Web.UI.WebControls.Label lblUserAddress;
        
        protected global::System.Web.UI.WebControls.Label lblTotalTickets;
        
        protected global::System.Web.UI.WebControls.Label lblTotalPaid;
        
        protected global::System.Web.UI.WebControls.Label lblTotalBookings;
        
        protected global::System.Web.UI.WebControls.GridView gvUserTickets;
        
        protected global::System.Web.UI.WebControls.Panel pnlNoData;
    }
}
